name: Run LangChain Agent

on:
  push:
    branches:
      - main
      - feature-code-dev
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    # 🔐 Secrets injected ONCE at job level
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      # ✅ Safe verification (does NOT print key)
      - name: Verify OpenAI key is available
        run: |
          echo "OPENAI_API_KEY length: ${#OPENAI_API_KEY}"
          echo "TAVILY_API_KEY length: ${#TAVILY_API_KEY}"

      - name: Run LangChain Agent
        run: python Module1.py
