name: Run LLM Agent

on:
  push:
    branches:
      - main
      - feature-code-dev

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Optional: Debug that secrets are available
      - name: Debug secrets
        run: |
          echo "OPENAI_API_KEY set: ${OPENAI_API_KEY:+Yes}"
          echo "TAVILY_API_KEY set: ${TAVILY_API_KEY:+Yes}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}

      # 5️⃣ Run Python script with secrets
      - name: Run Python Agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: python Module1.py
